CREATE TABLE platform (id varchar(128) PRIMARY KEY NOT NULL, doc JSONB NOT NULL);
CREATE TABLE channel (id varchar(128) PRIMARY KEY NOT NULL, doc JSONB NOT NULL);
CREATE TABLE collection (id varchar(128) PRIMARY KEY NOT NULL, doc JSONB NOT NULL);
CREATE TABLE promotion (id varchar(128) PRIMARY KEY NOT NULL, doc JSONB NOT NULL);
CREATE TABLE video (id varchar(128) PRIMARY KEY NOT NULL, doc JSONB NOT NULL);
CREATE TABLE view (id varchar(128) PRIMARY KEY NOT NULL, doc JSONB NOT NULL);
